### ISSUE TITLE
Fails with @keyframes

### ISSUE THREAD

**Issue by aelyseev** [tuchk4/rockey#5]
Looks that parser fails with `@keyframes`.

```css
.LoadingBl {
    color: ${({txt}) => txt};
    font: 300 24px/#{$height} sans-serif;
    background: ${({background}) => background};
    text-align: center;
    height: ${({height}) => height};

    &:after {
        content: ' .';
        font-family: Times, sans-serif;
        animation: dots 1200ms steps(5, end) infinite;
    }
}

@keyframes dots {
    0%, 20% {
        color: ${({txt}) => txt};
        text-shadow: 0.4em 0 0 ${({background}) => background},
        0.8em 0 0 ${({background}) => background};
    }
    40% {
        color: ${({txt}) => txt};
        text-shadow: 0.4em 0 0 ${({background}) => background},
        0.8em 0 0 ${({background}) => background};
    }
    60% {
        text-shadow: 0.4em 0 0 ${({txt}) => txt},
        0.8em 0 0 ${({background}) => background};
    }
    80%, 100% {
        text-shadow: 0.4em 0 0 ${({txt}) => txt},
        0.8em 0 0 ${({txt}) => txt};
    }
}
```
