### ISSUE TITLE
@media gets overridden by default styles

### ISSUE THREAD

**Issue by mlshv** [tuchk4/rockey#7]
This code
```css
Button {
  display: block;
  
  @media screen and (min-width: 48rem) {
    display: none;
  }
}
```
gets parsed into
```css
@media screen and (min-width: 48rem) {
    .__Button__hash__ {
        display: none;
    }
}

.__Button__hash__ {
    display: block;
}
```
which results in `display: block` on any screen, because `@media` gets overridden by `.__Button__hash__`
